//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OS.Localization.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Languages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Languages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OS.Localization.Resources.Languages", typeof(Languages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced Data.
        /// </summary>
        internal static string ADVANCED_DATA {
            get {
                return ResourceManager.GetString("ADVANCED_DATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See live parameters with values.
        /// </summary>
        internal static string ADVANCED_DATA_DESCRIPTION {
            get {
                return ResourceManager.GetString("ADVANCED_DATA_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        internal static string BACK {
            get {
                return ResourceManager.GetString("BACK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bluetooth Device.
        /// </summary>
        internal static string BLUETOOH_DEVICE {
            get {
                return ResourceManager.GetString("BLUETOOH_DEVICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bluetooth.
        /// </summary>
        internal static string BLUETOOTH {
            get {
                return ResourceManager.GetString("BLUETOOTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bluetooth/USB.
        /// </summary>
        internal static string BLUETOOTH_USB {
            get {
                return ResourceManager.GetString("BLUETOOTH_USB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        internal static string CLEAR {
            get {
                return ResourceManager.GetString("CLEAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear DTCs and freeze frame data?.
        /// </summary>
        internal static string CLEAR_DTCS_PROMPT {
            get {
                return ResourceManager.GetString("CLEAR_DTCS_PROMPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Diagnostic Trouble Codes.
        /// </summary>
        internal static string CLEAR_DTCS_TITLE {
            get {
                return ResourceManager.GetString("CLEAR_DTCS_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *** Device Not Set ***.
        /// </summary>
        internal static string COMMUNICATION_DEVICE_NOT_SETUP {
            get {
                return ResourceManager.GetString("COMMUNICATION_DEVICE_NOT_SETUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting to.
        /// </summary>
        internal static string CONNECTING_TO {
            get {
                return ResourceManager.GetString("CONNECTING_TO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacting Vehicle.
        /// </summary>
        internal static string CONTACTING_VEHICLE {
            get {
                return ResourceManager.GetString("CONTACTING_VEHICLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device.
        /// </summary>
        internal static string DEVICE {
            get {
                return ResourceManager.GetString("DEVICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device Type.
        /// </summary>
        internal static string DEVICE_TYPE {
            get {
                return ResourceManager.GetString("DEVICE_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        internal static string DONE {
            get {
                return ResourceManager.GetString("DONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DTCs.
        /// </summary>
        internal static string DTCs {
            get {
                return ResourceManager.GetString("DTCs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read and clear error codes.
        /// </summary>
        internal static string DTCs_DESCRIPTION {
            get {
                return ResourceManager.GetString("DTCs_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string EDIT {
            get {
                return ResourceManager.GetString("EDIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string ENGLISH {
            get {
                return ResourceManager.GetString("ENGLISH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string ERROR {
            get {
                return ResourceManager.GetString("ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t forget to recover your hardware from the vehicle.
        /// </summary>
        internal static string EXIT_PROMPT1 {
            get {
                return ResourceManager.GetString("EXIT_PROMPT1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue to Exit?.
        /// </summary>
        internal static string EXIT_PROMPT2 {
            get {
                return ResourceManager.GetString("EXIT_PROMPT2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Header.
        /// </summary>
        internal static string HEADER {
            get {
                return ResourceManager.GetString("HEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        internal static string INFORMATION {
            get {
                return ResourceManager.GetString("INFORMATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View the general status reported from the system.
        /// </summary>
        internal static string INFORMATION_DESCRIPTION {
            get {
                return ResourceManager.GetString("INFORMATION_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initializing.
        /// </summary>
        internal static string INITIALIZING {
            get {
                return ResourceManager.GetString("INITIALIZING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP Address.
        /// </summary>
        internal static string IP_ADDRESS {
            get {
                return ResourceManager.GetString("IP_ADDRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP Port.
        /// </summary>
        internal static string IP_PORT {
            get {
                return ResourceManager.GetString("IP_PORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string LANGUAGE {
            get {
                return ResourceManager.GetString("LANGUAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main Features.
        /// </summary>
        internal static string MAIN_FEATURES {
            get {
                return ResourceManager.GetString("MAIN_FEATURES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manufacturers.
        /// </summary>
        internal static string MANUFACTURERS {
            get {
                return ResourceManager.GetString("MANUFACTURERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metric.
        /// </summary>
        internal static string METRIC {
            get {
                return ResourceManager.GetString("METRIC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metric Units.
        /// </summary>
        internal static string METRIC_UNITS {
            get {
                return ResourceManager.GetString("METRIC_UNITS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model.
        /// </summary>
        internal static string MODEL {
            get {
                return ResourceManager.GetString("MODEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App ID.
        /// </summary>
        internal static string MSG_APP_ID {
            get {
                return ResourceManager.GetString("MSG_APP_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        internal static string MSG_APPLY {
            get {
                return ResourceManager.GetString("MSG_APPLY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto.
        /// </summary>
        internal static string MSG_AUTO {
            get {
                return ResourceManager.GetString("MSG_AUTO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bluetooth device not open.
        /// </summary>
        internal static string MSG_BLUETOOTH_DEVICE_NOT_OPEN {
            get {
                return ResourceManager.GetString("MSG_BLUETOOTH_DEVICE_NOT_OPEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bluetooth is disabled on this device.
        /// </summary>
        internal static string MSG_BLUETOOTH_DISABLED {
            get {
                return ResourceManager.GetString("MSG_BLUETOOTH_DISABLED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bluetooth error.
        /// </summary>
        internal static string MSG_BLUETOOTH_ERROR {
            get {
                return ResourceManager.GetString("MSG_BLUETOOTH_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string MSG_CANCEL {
            get {
                return ResourceManager.GetString("MSG_CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete.
        /// </summary>
        internal static string MSG_COMPLETE {
            get {
                return ResourceManager.GetString("MSG_COMPLETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected.
        /// </summary>
        internal static string MSG_CONNECTED {
            get {
                return ResourceManager.GetString("MSG_CONNECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact MikeOtterbine@Gmail.com.
        /// </summary>
        internal static string MSG_CONTACT_MIKE {
            get {
                return ResourceManager.GetString("MSG_CONTACT_MIKE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For Install Code.
        /// </summary>
        internal static string MSG_CONTACT_MIKE1 {
            get {
                return ResourceManager.GetString("MSG_CONTACT_MIKE1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy ID.
        /// </summary>
        internal static string MSG_COPY_ID {
            get {
                return ResourceManager.GetString("MSG_COPY_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to access device.
        /// </summary>
        internal static string MSG_DEVICE_ACCESS_FAILURE {
            get {
                return ResourceManager.GetString("MSG_DEVICE_ACCESS_FAILURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device not connected.
        /// </summary>
        internal static string MSG_DEVICE_NOT_CONNECTED {
            get {
                return ResourceManager.GetString("MSG_DEVICE_NOT_CONNECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *** Device Not Set ***.
        /// </summary>
        internal static string MSG_DEVICE_NOT_SET {
            get {
                return ResourceManager.GetString("MSG_DEVICE_NOT_SET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device Open Failure.
        /// </summary>
        internal static string MSG_DEVICE_OPEN_FAILURE {
            get {
                return ResourceManager.GetString("MSG_DEVICE_OPEN_FAILURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emission DTCs.
        /// </summary>
        internal static string MSG_EMISSION_DTCS {
            get {
                return ResourceManager.GetString("MSG_EMISSION_DTCS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *** ERROR ***.
        /// </summary>
        internal static string MSG_ERROR {
            get {
                return ResourceManager.GetString("MSG_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string MSG_EXIT {
            get {
                return ResourceManager.GetString("MSG_EXIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit Application.
        /// </summary>
        internal static string MSG_EXIT_APPLICATION {
            get {
                return ResourceManager.GetString("MSG_EXIT_APPLICATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fault.
        /// </summary>
        internal static string MSG_FAULT {
            get {
                return ResourceManager.GetString("MSG_FAULT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install Code.
        /// </summary>
        internal static string MSG_INSTALL_CODE {
            get {
                return ResourceManager.GetString("MSG_INSTALL_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid USB.
        /// </summary>
        internal static string MSG_INVALID_USB {
            get {
                return ResourceManager.GetString("MSG_INVALID_USB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart App For All Changes To Take Effect.
        /// </summary>
        internal static string MSG_LANGUAGE_CHANGE_POPUP_TEXT {
            get {
                return ResourceManager.GetString("MSG_LANGUAGE_CHANGE_POPUP_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Language.
        /// </summary>
        internal static string MSG_LANGUAGE_CHANGE_POPUP_TITLE {
            get {
                return ResourceManager.GetString("MSG_LANGUAGE_CHANGE_POPUP_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Live Data.
        /// </summary>
        internal static string MSG_LIVE_DATA {
            get {
                return ResourceManager.GetString("MSG_LIVE_DATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DTC Light On.
        /// </summary>
        internal static string MSG_MIL_ON {
            get {
                return ResourceManager.GetString("MSG_MIL_ON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Bluetooth device found.
        /// </summary>
        internal static string MSG_NO_BLUETOOTH_DEVICE_FOUND {
            get {
                return ResourceManager.GetString("MSG_NO_BLUETOOTH_DEVICE_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *** No Data ***.
        /// </summary>
        internal static string MSG_NO_DATA {
            get {
                return ResourceManager.GetString("MSG_NO_DATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Data Reported.
        /// </summary>
        internal static string MSG_NO_DATA_REPORTED {
            get {
                return ResourceManager.GetString("MSG_NO_DATA_REPORTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Response From System.
        /// </summary>
        internal static string MSG_NO_RESPONSE_SYSTEM {
            get {
                return ResourceManager.GetString("MSG_NO_RESPONSE_SYSTEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Response From Vehicle.
        /// </summary>
        internal static string MSG_NO_RESPONSE_VEHICLE {
            get {
                return ResourceManager.GetString("MSG_NO_RESPONSE_VEHICLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Ready.
        /// </summary>
        internal static string MSG_NOT_READY {
            get {
                return ResourceManager.GetString("MSG_NOT_READY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        internal static string MSG_OK {
            get {
                return ResourceManager.GetString("MSG_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation Cancelled.
        /// </summary>
        internal static string MSG_OPERATION_CANCELLED {
            get {
                return ResourceManager.GetString("MSG_OPERATION_CANCELLED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permissions required.
        /// </summary>
        internal static string MSG_PERMISSIONS_REQUIRED {
            get {
                return ResourceManager.GetString("MSG_PERMISSIONS_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable To get ports list.
        /// </summary>
        internal static string MSG_PORTS_LIST_ERROR {
            get {
                return ResourceManager.GetString("MSG_PORTS_LIST_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready.
        /// </summary>
        internal static string MSG_READY {
            get {
                return ResourceManager.GetString("MSG_READY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset DTC command sent.
        /// </summary>
        internal static string MSG_RESET_COMMAND_SENT {
            get {
                return ResourceManager.GetString("MSG_RESET_COMMAND_SENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending....
        /// </summary>
        internal static string MSG_SENDING {
            get {
                return ResourceManager.GetString("MSG_SENDING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Since DTCs Cleared.
        /// </summary>
        internal static string MSG_SINCE_DTCS_CLEARED {
            get {
                return ResourceManager.GetString("MSG_SINCE_DTCS_CLEARED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        internal static string MSG_SUCCESS {
            get {
                return ResourceManager.GetString("MSG_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No USB available.
        /// </summary>
        internal static string NO_USB_AVAILABLE {
            get {
                return ResourceManager.GetString("NO_USB_AVAILABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OBDII PIDS.
        /// </summary>
        internal static string OBDII_PIDS {
            get {
                return ResourceManager.GetString("OBDII_PIDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause.
        /// </summary>
        internal static string PAUSE {
            get {
                return ResourceManager.GetString("PAUSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ambient Air Temperature.
        /// </summary>
        internal static string PIDS_AAT_DESCR {
            get {
                return ResourceManager.GetString("PIDS_AAT_DESCR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Barometric Pressure.
        /// </summary>
        internal static string PIDS_BARO_DESCR {
            get {
                return ResourceManager.GetString("PIDS_BARO_DESCR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cat Temp Bank 1 Sensor 1.
        /// </summary>
        internal static string PIDS_CATEMP11_DESCR {
            get {
                return ResourceManager.GetString("PIDS_CATEMP11_DESCR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cat Temp Bank 1 Sensor 2.
        /// </summary>
        internal static string PIDS_CATEMP12_DESCR {
            get {
                return ResourceManager.GetString("PIDS_CATEMP12_DESCR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cat Temp Bank 2 Sensor 1.
        /// </summary>
        internal static string PIDS_CATEMP21_DESCR {
            get {
                return ResourceManager.GetString("PIDS_CATEMP21_DESCR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cat Temp Bank 2 Sensor 2.
        /// </summary>
        internal static string PIDS_CATEMP22_DESCR {
            get {
                return ResourceManager.GetString("PIDS_CATEMP22_DESCR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distance since DTCs cleared.
        /// </summary>
        internal static string PIDS_CLR_DIST_DESCR {
            get {
                return ResourceManager.GetString("PIDS_CLR_DIST_DESCR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Engine Coolant Temperature.
        /// </summary>
        internal static string PIDS_ECT_DESCR {
            get {
                return ResourceManager.GetString("PIDS_ECT_DESCR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commanded EGR.
        /// </summary>
        internal static string PIDS_EGR_CMD_PCT_DESCR {
            get {
                return ResourceManager.GetString("PIDS_EGR_CMD_PCT_DESCR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EGR Error.
        /// </summary>
        internal static string PIDS_EGR_ERR_PCT_DESCR {
            get {
                return ResourceManager.GetString("PIDS_EGR_ERR_PCT_DESCR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commanded EVAP Purge.
        /// </summary>
        internal static string PIDS_EVAP_PCT_DESCR {
            get {
                return ResourceManager.GetString("PIDS_EVAP_PCT_DESCR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EVAP Pressure.
        /// </summary>
        internal static string PIDS_EVAP_VP_DESCR {
            get {
                return ResourceManager.GetString("PIDS_EVAP_VP_DESCR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fuel Level.
        /// </summary>
        internal static string PIDS_FLI_DESCR {
            get {
                return ResourceManager.GetString("PIDS_FLI_DESCR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fuel Rail Pressure.
        /// </summary>
        internal static string PIDS_FRP_DESCR {
            get {
                return ResourceManager.GetString("PIDS_FRP_DESCR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fuel Rail Pressure (gauge).
        /// </summary>
        internal static string PIDS_FRP_G_DESCR {
            get {
                return ResourceManager.GetString("PIDS_FRP_G_DESCR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fuel Rail Pressure Relative to Manifold Vacuum.
        /// </summary>
        internal static string PIDS_FRP_MV_DESCR {
            get {
                return ResourceManager.GetString("PIDS_FRP_MV_DESCR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fuel System 1 Status.
        /// </summary>
        internal static string PIDS_FUEL_SYSTEM1_STATUS {
            get {
                return ResourceManager.GetString("PIDS_FUEL_SYSTEM1_STATUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fuel System 2 Status.
        /// </summary>
        internal static string PIDS_FUEL_SYSTEM2_STATUS {
            get {
                return ResourceManager.GetString("PIDS_FUEL_SYSTEM2_STATUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fuel System Status.
        /// </summary>
        internal static string PIDS_FUELSYS_DESCR {
            get {
                return ResourceManager.GetString("PIDS_FUELSYS_DESCR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Air Intake Temperature.
        /// </summary>
        internal static string PIDS_IAT_DESCR {
            get {
                return ResourceManager.GetString("PIDS_IAT_DESCR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fuel/Air Commanded Equiv. Ratio.
        /// </summary>
        internal static string PIDS_LAMBDA_DESCR {
            get {
                return ResourceManager.GetString("PIDS_LAMBDA_DESCR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Absolute Load.
        /// </summary>
        internal static string PIDS_LOAD_ABS_DESCR {
            get {
                return ResourceManager.GetString("PIDS_LOAD_ABS_DESCR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Engine Load (calculated).
        /// </summary>
        internal static string PIDS_LOAD_PCT_DESCR {
            get {
                return ResourceManager.GetString("PIDS_LOAD_PCT_DESCR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Long-term fuel trim for bank 1/3.
        /// </summary>
        internal static string PIDS_LONGFT13_DESCR {
            get {
                return ResourceManager.GetString("PIDS_LONGFT13_DESCR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Long-term fuel trim for bank 2/4.
        /// </summary>
        internal static string PIDS_LONGFT24_DESCR {
            get {
                return ResourceManager.GetString("PIDS_LONGFT24_DESCR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mass Air Flow.
        /// </summary>
        internal static string PIDS_MAF_DESCR {
            get {
                return ResourceManager.GetString("PIDS_MAF_DESCR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intake Manifold Air Pressure.
        /// </summary>
        internal static string PIDS_MAP_DESCR {
            get {
                return ResourceManager.GetString("PIDS_MAP_DESCR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distance with MIL on.
        /// </summary>
        internal static string PIDS_MIL_DIST_DESCR {
            get {
                return ResourceManager.GetString("PIDS_MIL_DIST_DESCR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O2 Sensor 1 Bank 1.
        /// </summary>
        internal static string PIDS_O2S11_DESCR {
            get {
                return ResourceManager.GetString("PIDS_O2S11_DESCR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O2 Sensor 2 Bank 1.
        /// </summary>
        internal static string PIDS_O2S12_DESCR {
            get {
                return ResourceManager.GetString("PIDS_O2S12_DESCR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O2 Sensor 3 Bank 1.
        /// </summary>
        internal static string PIDS_O2S13_DESCR {
            get {
                return ResourceManager.GetString("PIDS_O2S13_DESCR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O2 Sensor 4 Bank 1.
        /// </summary>
        internal static string PIDS_O2S14_DESCR {
            get {
                return ResourceManager.GetString("PIDS_O2S14_DESCR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O2 Sensor 1 Bank 2.
        /// </summary>
        internal static string PIDS_O2S21_DESCR {
            get {
                return ResourceManager.GetString("PIDS_O2S21_DESCR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O2 Sensor 2 Bank 2.
        /// </summary>
        internal static string PIDS_O2S22_DESCR {
            get {
                return ResourceManager.GetString("PIDS_O2S22_DESCR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O2 Sensor 3 Bank 2.
        /// </summary>
        internal static string PIDS_O2S23_DESCR {
            get {
                return ResourceManager.GetString("PIDS_O2S23_DESCR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O2 Sensor 4 Bank 2.
        /// </summary>
        internal static string PIDS_O2S24_DESCR {
            get {
                return ResourceManager.GetString("PIDS_O2S24_DESCR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Engine RPM.
        /// </summary>
        internal static string PIDS_RPM_DESCR {
            get {
                return ResourceManager.GetString("PIDS_RPM_DESCR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time since engine start.
        /// </summary>
        internal static string PIDS_RUNTM_DESCR {
            get {
                return ResourceManager.GetString("PIDS_RUNTM_DESCR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Short-term fuel trim for bank 1/3.
        /// </summary>
        internal static string PIDS_SHRTFT13_DESCR {
            get {
                return ResourceManager.GetString("PIDS_SHRTFT13_DESCR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Short-term fuel trim for bank 2/4.
        /// </summary>
        internal static string PIDS_SHRTFT24_DESCR {
            get {
                return ResourceManager.GetString("PIDS_SHRTFT24_DESCR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spark Advance (non-mechanical).
        /// </summary>
        internal static string PIDS_SPARKADV_DESCR {
            get {
                return ResourceManager.GetString("PIDS_SPARKADV_DESCR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Throttle Position.
        /// </summary>
        internal static string PIDS_THROTTLE_POS_DESCR {
            get {
                return ResourceManager.GetString("PIDS_THROTTLE_POS_DESCR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relative Throttle Position.
        /// </summary>
        internal static string PIDS_TP_R_DESCR {
            get {
                return ResourceManager.GetString("PIDS_TP_R_DESCR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commanded Throttle Actuator Position.
        /// </summary>
        internal static string PIDS_VPWR_CMD_DESCR {
            get {
                return ResourceManager.GetString("PIDS_VPWR_CMD_DESCR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Volts.
        /// </summary>
        internal static string PIDS_VPWR_DESCR {
            get {
                return ResourceManager.GetString("PIDS_VPWR_DESCR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle Speed Sensor.
        /// </summary>
        internal static string PIDS_VSS_DESCR {
            get {
                return ResourceManager.GetString("PIDS_VSS_DESCR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warm ups since DTCs cleared.
        /// </summary>
        internal static string PIDS_WARM_UPS_DESCR {
            get {
                return ResourceManager.GetString("PIDS_WARM_UPS_DESCR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plot Height.
        /// </summary>
        internal static string PLOT_HEIGHT {
            get {
                return ResourceManager.GetString("PLOT_HEIGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Protocol.
        /// </summary>
        internal static string PROTOCOL {
            get {
                return ResourceManager.GetString("PROTOCOL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read.
        /// </summary>
        internal static string READ {
            get {
                return ResourceManager.GetString("READ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reading DTCs.
        /// </summary>
        internal static string READING_DTCS {
            get {
                return ResourceManager.GetString("READING_DTCS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reading PIDs.
        /// </summary>
        internal static string READING_PIDS {
            get {
                return ResourceManager.GetString("READING_PIDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reading Status....
        /// </summary>
        internal static string READING_STATUS {
            get {
                return ResourceManager.GetString("READING_STATUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        internal static string REFRESH {
            get {
                return ResourceManager.GetString("REFRESH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Model.
        /// </summary>
        internal static string SELECT_MODEL {
            get {
                return ResourceManager.GetString("SELECT_MODEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the model and manufacturer.
        /// </summary>
        internal static string SELECT_MODEL_DESCRIPTION {
            get {
                return ResourceManager.GetString("SELECT_MODEL_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serial Baud Rate.
        /// </summary>
        internal static string SERIAL_BAUD_RATE {
            get {
                return ResourceManager.GetString("SERIAL_BAUD_RATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string SETTINGS {
            get {
                return ResourceManager.GetString("SETTINGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        internal static string START {
            get {
                return ResourceManager.GetString("START", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Recording.
        /// </summary>
        internal static string START_RECORDING {
            get {
                return ResourceManager.GetString("START_RECORDING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        internal static string STOP {
            get {
                return ResourceManager.GetString("STOP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *** All Tests Complete ***.
        /// </summary>
        internal static string STRING_ALL_TESTS_COMPLETE {
            get {
                return ResourceManager.GetString("STRING_ALL_TESTS_COMPLETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Establishing Link.
        /// </summary>
        internal static string STRING_ESTABLISHING_LINK {
            get {
                return ResourceManager.GetString("STRING_ESTABLISHING_LINK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initializing.
        /// </summary>
        internal static string STRING_INITIALIZING {
            get {
                return ResourceManager.GetString("STRING_INITIALIZING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Codes Found.
        /// </summary>
        internal static string STRING_NO_CODES_FOUND {
            get {
                return ResourceManager.GetString("STRING_NO_CODES_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *** No Data ***.
        /// </summary>
        internal static string STRING_NO_DATA {
            get {
                return ResourceManager.GetString("STRING_NO_DATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Not Set&gt;.
        /// </summary>
        internal static string STRING_NOT_SET {
            get {
                return ResourceManager.GetString("STRING_NOT_SET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searching....
        /// </summary>
        internal static string STRING_SEARCHING {
            get {
                return ResourceManager.GetString("STRING_SEARCHING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trouble Codes.
        /// </summary>
        internal static string TROUBLE_CODES {
            get {
                return ResourceManager.GetString("TROUBLE_CODES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Units.
        /// </summary>
        internal static string UNITS_MEAS {
            get {
                return ResourceManager.GetString("UNITS_MEAS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USB.
        /// </summary>
        internal static string USB {
            get {
                return ResourceManager.GetString("USB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle Status.
        /// </summary>
        internal static string VEHICLE_STATUS {
            get {
                return ResourceManager.GetString("VEHICLE_STATUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WiFi.
        /// </summary>
        internal static string WIFI {
            get {
                return ResourceManager.GetString("WIFI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network/WiFi.
        /// </summary>
        internal static string WIFI_TYPE_DESCRIPTOR {
            get {
                return ResourceManager.GetString("WIFI_TYPE_DESCRIPTOR", resourceCulture);
            }
        }
    }
}
